# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

Style/FrozenStringLiteralComment:
  Enabled: false

GlobalVars:
  Description: Do not introduce global variables.
  Enabled: false

UselessAssignment:
  Description: Useless assignment to variable.
  Enabled: false

Metrics/AbcSize:
  Description: Assignment Branch Condition size for conn_space is too high.
  Enabled: false

Metrics/MethodLength:
  Description: Method has too many lines.
  Enabled: false

RSpec/VariableName:
  Description: Use snake_case for variable names.
  EnforcedStyle: "snake_case"
  Enabled: false

Metrics/BlockNesting:
  Description:  Avoid more than 3 levels of block nesting.
  Enabled: false

AllCops:
  Exclude:
    - 'env/**/*'
  Include:
    - '**/*.rb'
    - '**/*.drc'
